#server:
#  port: 8080
#
#spring:
#  application:
#    name: customer
#
#  datasource:
#    username: 'erest'
#    url: jdbc:postgresql://localhost:5432/customer
#    password: 'password'
#    jpa:
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          format_sql: 'true'
#
#      hibernate:
#        ddl-auto: update
#      show-sql: 'true'


server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    username: 'erest'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/customer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
